x-debug-env: &debug-env
  - DATABASE_URL=postgresql://root@127.0.0.1:26257/nightworkers?schema=nw-chips-bank&sslmode=disable
  - HTTPS_HOST=localhost
  - CORS_ALLOWED_URL=http://localhost

name: nightworkers-crosschain-service
services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    # depends_on:
    #   database:
    #     condition: service_healthy
    ports:
      - "19229:9229"
    command: [
      # "--inspect-brk=0.0.0.0:9229", 
      "scraper"
    ]
    environment: *debug-env
    env_file:
      - ./.env
    volumes:
      - ./deployed.json:/home/node/app/dist/deployed.json:ro
      - ./networks.json:/home/node/app/dist/networks.json:ro
